// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-4PJKcHIYwOz5u0v8eH-FpRi4JxF0tYM',
    appId: '1:736255883882:android:22804be22ee25d1923a813',
    messagingSenderId: '736255883882',
    projectId: 'recordatorios-app-a8081',
    storageBucket: 'recordatorios-app-a8081.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqheql3WjtEsKByBnRtRoNCsVIJx5LzP8',
    appId: '1:736255883882:ios:511c85f6907f655423a813',
    messagingSenderId: '736255883882',
    projectId: 'recordatorios-app-a8081',
    storageBucket: 'recordatorios-app-a8081.appspot.com',
    iosBundleId: 'com.example.recordatoriosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqheql3WjtEsKByBnRtRoNCsVIJx5LzP8',
    appId: '1:736255883882:ios:b179e9830e9ddb7e23a813',
    messagingSenderId: '736255883882',
    projectId: 'recordatorios-app-a8081',
    storageBucket: 'recordatorios-app-a8081.appspot.com',
    iosBundleId: 'com.example.recordatoriosApp.RunnerTests',
  );
}
